//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Insert PriceType ******/
        ///INSERT INTO [dbo].[BASE_PriceType]([priceType],[datestamp],[status]) VALUES (&apos;LP without VAT&apos;,&apos;1/30/2017&apos;,1)
        ///GO
        ///INSERT INTO [dbo].[BASE_PriceType]([priceType],[datestamp],[status]) VALUES (&apos;LP with VAT&apos;,&apos;1/30/2017&apos;,1)
        ///GO
        ////****** Insert Route ******/
        ///INSERT INTO [dbo].[BASE_Route] ([name] ,[datestamp] ,[status]) VALUES (&apos;Route1&apos; ,&apos;2/05/2017&apos; ,1)
        ///GO
        ////****** Insert SalesMan ******/
        ///INSERT INTO [dbo].[BASE_SalesMan] ([name] ,[datestamp] ,[status]) VALUES (&apos; &apos; ,&apos;2/05/201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddInitialData {
            get {
                return ResourceManager.GetString("AddInitialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_GLOBAL_UpdateTransaction]    Script Date: 12/1/2017 5:25:05 PM ******/
        ///-- =============================================
        ///-- Author:		Eddie Cabellon
        ///-- ALTER date: 3/15/2017
        ///-- Description:	Update Product Transaction and Adjust the stocks
        ///-- =============================================				 
        ///CREATE PROCEDURE [dbo].[sp_GLOBAL_UpdateTransaction] 
        ///(
        ///	@ProdIndex	int
        ///	,@ProductCode 	nvarchar(50)
        ///	,@DocType 	int
        ///	,@DocNo		nvarchar(20)
        ///	,@DocDate	nvarchar(60) 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlterDatabase {
            get {
                return ResourceManager.GetString("AlterDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  UserDefinedFunction [dbo].[GetPhysicalCountTotalQty]    Script Date: 07/15/2017 01:28:37 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Eddie Cabellon
        ///-- Create date: 7/14/2017
        ///-- Description:	Function that Return total qty of physical count in pieces
        ///-- =============================================
        ///CREATE FUNCTION [dbo].[GetPhysicalCountTotalQty]
        ///(   @prodindex		int,
        ///	@MonthCycle		int,
        ///	@YearCycle		int,
        ///	@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateFunction {
            get {
                return ResourceManager.GetString("CreateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[BASE_Carrier]    Script Date: 3/15/2017 3:35:26 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[BASE_Carrier](
        ///	[name] [nvarchar](20) NOT NULL,
        ///	[datestamp] [datetime] NOT NULL,
        ///	[status] [bit] NOT NULL
        ///) ON [PRIMARY]
        ///
        ///GO
        ////****** Object:  Table [dbo].[BASE_UOM]    Script Date: 3/15/2017 3:35:26 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[BASE_UOM](
        ///	[_UOMIndex] [int] IDENTITY NOT NULL, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateMasterTable {
            get {
                return ResourceManager.GetString("CreateMasterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[GLOBAL_DocType]    Script Date: 1/20/2017 10:28:49 AM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///CREATE TABLE [dbo].[GLOBAL_DocType](
        ///	[_DocTypeIndex]		[int] IDENTITY(1,1) NOT NULL,
        ///	[name]				[nvarchar](30) NOT NULL,
        ///	[docno]				[nvarchar](10) NOT NULL,
        ///	[affix]				[nvarchar](5) NULL,
        ///	[suffix]			[nvarchar](5) NULL,
        ///	[datestamp]			[datetime] NOT NULL,
        ///	[status]			[bit] NOT NULL,
        /// CONSTRAINT [PK_GLOBAL_DocType] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_DocTypeInd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateProdTrans {
            get {
                return ResourceManager.GetString("CreateProdTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_REPORT_StockPosition]    Script Date: 03/19/2017 09:47:09 ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Eddie Cabellon
        ///-- Create date: 3/15/2017
        ///-- Description:	Generate Stock position report
        ///-- =============================================				 
        ///CREATE PROCEDURE [dbo].[sp_REPORT_StockPosition]
        ///(	@isG	bit=1 
        ///)
        ///AS
        ///IF @isG = 1
        ///BEGIN
        ///	SELECT p._prodindex,P.productcode,P.ccode,P.sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateReports {
            get {
                return ResourceManager.GetString("CreateReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [dbSettings]
        ///GO
        ///
        ////****** Object:  Table [dbo].[BASE_BRANCH]    Script Date: 8/19/2017 12:16:06 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///CREATE TABLE [dbo].[BASE_BRANCH](
        ///	[_BranchIndex] [int] IDENTITY(1,1) NOT NULL,
        ///	[Name] [nvarchar](100) NOT NULL,
        ///	[DateStamp] [datetime] NOT NULL,
        ///PRIMARY KEY CLUSTERED 
        ///(
        ///	[_BranchIndex] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSettingsTable {
            get {
                return ResourceManager.GetString("CreateSettingsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_BASE_getSalesMan]    Script Date: 3/20/2017 1:37:44 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Eddie Cabellon
        ///-- Create date: 3/15/2017
        ///-- Description:	Get SalesMan details
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[sp_BASE_GetSalesMan]
        ///	@smanindex		int=0
        ///AS
        ///BEGIN
        ///    -- Insert statements for procedure here
        ///	IF (@smanindex = 0) 
        ///		BEGIN
        ///		S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSPGetters {
            get {
                return ResourceManager.GetString("CreateSPGetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_insertLOGS]    Script Date: 3/17/2017 3:27:07 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		Eddie Cabellon
        ///-- Create date: 3/15/2017
        ///-- Description:	Insert Logs for revise quantity and amount
        ///-- =============================================
        ///CREATE PROCEDURE [dbo].[sp_LOGS_InsertLOGS]
        ///(	@ProdIndex			[int],
        ///	@DocType			[int],
        ///	@DocNo				[nvarchar](20),
        ///	@DocDate			[datetime],
        ///	@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSPInsert {
            get {
                return ResourceManager.GetString("CreateSPInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1
        ///&lt;limiter&gt;.
        /// </summary>
        internal static string Database_version {
            get {
                return ResourceManager.GetString("Database_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[sp_GLOBAL_UpdateTransaction]
        ///&lt;limiter&gt;
        ///ALTER PROCEDURE [dbo].[sp_REPORT_InsertElectronicStockard]
        ///&lt;limiter&gt;.
        /// </summary>
        internal static string DatabaseUpdateDetails {
            get {
                return ResourceManager.GetString("DatabaseUpdateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use master 
        ///GO
        ///EXEC xp_instance_regwrite N&apos;HKEY_LOCAL_MACHINE&apos;, N&apos;Software\Microsoft\MSSQLServer\MSSQLServer&apos;, N&apos;LoginMode&apos;, REG_DWORD, 2
        ///GO
        ///ALTER LOGIN [sa] WITH PASSWORD=N&apos;tqbfjotld&apos;
        ///GO
        ///IF NOT EXISTS 
        ///    (SELECT name  
        ///     FROM master.sys.server_principals
        ///     WHERE name = &apos;vgl_data&apos;)
        ///BEGIN
        ///	DECLARE @SQLCommand nvarchar(40)
        ///	CREATE LOGIN [vgl_data] WITH PASSWORD=N&apos;tqbfjotld&apos;, DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
        ///	EXEC master..sp_ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializeSQLUser {
            get {
                return ResourceManager.GetString("InitializeSQLUser", resourceCulture);
            }
        }
    }
}
